name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/wiki-discord-bot:latest

    - name: Logout from Docker Hub
      run: docker logout

    - name: Send Telegram notification
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.ALERT_TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=686700338 \
        -d text="Wiki Discord Bot pushed to dockerhub"
