name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest pymongo pytz

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..20}; do
            if mongosh --quiet --eval "db.runCommand({ping: 1})"; then
              echo "MongoDB is ready!"
              exit 0
            fi
            echo "Waiting for MongoDB..."
            sleep 5
          done
          exit 1

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest --no-header --no-summary -q

      - name: Send Telegram notification (Test Result)
        if: always()
        run: |
          STATUS="✅ Tests Passed!"
          if [ "${{ env.TESTS_FAILED }}" = "true" ]; then
            STATUS="❌ Tests Failed!"
          fi

          curl -s -X POST https://api.telegram.org/bot${{ secrets.ALERT_TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=686700338 \
          -d text="${STATUS} - Workflow: ${{ github.workflow }} - Commit: ${{ github.sha }}"


  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wiki-discord-bot:latest

      - name: Logout from Docker Hub
        run: docker logout

      - name: Send Telegram notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.ALERT_TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=686700338 \
          -d text="✅ Wiki Discord Bot pushed to Docker Hub successfully!"
